const FACES = ["2","3","4","5","6","7","8","9","10","J","Q","K","A"]
const HIGH_CARD = 1
const PAIR = 2
const TWO_PAIR = 3
const THREE_OF_A_KIND = 4
const STRAIGHT = 5
const FLUSH = 6
const FULL_HOUSE = 7
const FOUR_OF_A_KIND = 8
const STRAIGHT_FLUSH = 9
const ROYAL_FLUSH = 10
const VALID = -1
const HAND_RANKS =["High Card","Pair","Two Pair","Three of a Kind", "Straight", "Flush", "Full House", "Four Of A Kind", "Straight Flush", "Royal Flush"]
