all: sec3_1Q19 sec3_1Q20

sec3_1Q19: sec3_1Q19.cpp lagrange.cpp lagrange.h
	g++ sec3_1Q19.cpp lagrange.cpp -o Q19

sec3_1Q20: sec3_1Q20.cpp lagrange.cpp lagrange.h
	g++ sec3_1Q20.cpp lagrange.cpp -o Q20