all: prob3 prob5 prob1

prob3: prob3.cpp
	g++ prob3.cpp -larmadillo -D PROB_3 -o Q3

prob5: prob5.cpp
	g++ prob5.cpp -larmadillo -D PROB_5 -o Q5

prob1: prob1.cpp
	g++ prob1.cpp -larmadillo -D PROB_1 -o Q1