all: from_pounds

from_pounds: please_be_easy_the_last_question_killed_me.cpp lagrange.cpp lagrange.h naturalSpline.cpp naturalSpline.h
	g++ please_be_easy_the_last_question_killed_me.cpp lagrange.cpp naturalSpline.cpp -o from_pounds