all: prob9 prob11 prob13 prob17

prob9: prob9.cpp ../Section1/gaussianElim.cpp ../Section1/gaussianElim.h ../Section1/roundingCalc.cpp ../Section1/roundingCalc.h
	g++ prob9.cpp ../Section1/gaussianElim.cpp ../Section1/roundingCalc.cpp -D PROB_9 -o Q9

prob11: prob11.cpp ../Section1/gaussianElim.cpp ../Section1/gaussianElim.h ../Section1/roundingCalc.cpp ../Section1/roundingCalc.h
	g++ prob11.cpp ../Section1/gaussianElim.cpp ../Section1/roundingCalc.cpp -D PROB_11 -o Q11

prob13: prob13.cpp ../Section1/gaussianElim.cpp ../Section1/gaussianElim.h ../Section1/roundingCalc.cpp ../Section1/roundingCalc.h
	g++ prob13.cpp ../Section1/gaussianElim.cpp ../Section1/roundingCalc.cpp -D PROB_13 -o Q13

prob17: prob17.cpp ../Section1/gaussianElim.cpp ../Section1/gaussianElim.h ../Section1/roundingCalc.cpp ../Section1/roundingCalc.h
	g++ prob17.cpp ../Section1/gaussianElim.cpp ../Section1/roundingCalc.cpp -D PROB_17 -o Q17