all: sec3_5Q25 sec3_5Q26 sec3_5Q27

sec3_5Q25: sec3_5Q25.cpp naturalSpline.cpp naturalSpline.h
	g++ sec3_5Q25.cpp naturalSpline.cpp -o Q25

sec3_5Q26: sec3_5Q26.cpp naturalSpline.cpp naturalSpline.h
	g++ sec3_5Q26.cpp naturalSpline.cpp -o Q26

sec3_5Q27: sec3_5Q27.cpp
	g++ sec3_5Q27.cpp -o Q27