all: prob1a prob5a prob8

prob1a: prob1a.cpp
	g++ prob1a.cpp -larmadillo -D PROB_1A -o Q1

prob5a: prob5a.cpp
	g++ prob5a.cpp -larmadillo -D PROB_5A -o Q5

prob8: prob8a.cpp
	g++ prob8a.cpp -larmadillo -D PROB_8A -o Q8